language: node_js
dist: trusty
sudo: required
node_js:
- node
- '6'
cache:
  directories:
  - node_modules
install:
- npm install -g polymer-cli
- npm install
- polymer install
script:
- polymer build --add-service-worker
deploy:
  provider: firebase
  token:
    secure: BXsBv+LUTYEdDxA35DhIOsPwRZ4cda1NYaM3S5VScQksnlLqLooEjJa9RZo77+/csV4Mbt8Xr4Dgk1UlNVj863tR92SlzrWAPhQ3hyW7jKmsYAsx+XKsymDjkY6WEjvDCDbTZ7TCRjAW2ZGnl9nnL8r5rcbpt3a5+PRDP4BCkEp7A4xFide9A92WUlJQLWT3IMt/uZiGnbDb2PX/hvuN0KIp5SGmfeqPSbBt8kc4OKaF/Yh9X4Wmys/PbZf0wL0TgCmLCww37BWwvQKfEFNTYrUENpDULmAgM8c3p7xFzf307WGb1FTw5jAtgVwopG5iUL4ZGq0g9/9fOIWfTBLdGReiQBUfDxsLhpAi1ekGwg5ir8iUlxMntNV7xUOJsjX1u/hroUpTDR/xPQgAyJ5KQUsnmz2Ta725KjPSGal18N4oK3aL862EwR8g4Y12lZsPAGbPpshBvXanSnSN1JJMZZf/HzR0wCfXAdqU2/qSBSXxQlDDFIgdE23dSZGqEVXJ0zWRfBA8dzB/QpUFqunWGvVS9NmGqIctZKIhsoDhPPO7RTHiYmyRMltFQktvo5lXD1NkxlG1/mL6muPGSglYQMC1aY8LLRb1cZi5X4PYKj3MCOXqp5qXvAqnf60xj6cVGdMvblWNr2QhNH3QO5WLybPKLKIcwDjmCs0+5uCuK8c=
