language: node_js
dist: trusty
sudo: required
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- yarn global add polymer-cli
- polymer install
script: true
before_deploy:
- polymer build --add-service-worker
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: HRHzqxLhMApiMBm99FOH2ANwniFh7V0n1FvGcWt4EKPMEbJcfhmOpEwW5HFpILV50b1/NbwRTy4dMcwmVOBUpnBG3CzAQf4funxsAkm4sw2z6+rzIKCRzGW3sB7kHt7XuaXnmCNIsEV7mggig0AonmtaqCrwyx3U7d85/1PSQ0DottYKrzlabUEK7TKY2IJGp5uxWxXGdAMFbTXax5WeVBRuiYOy36RffJPh+r6S/wp5kZIr0j8YkJk79Prb/4jEJ2/sWIKOn7quO31M5GlUjzcgeTGht4Oc8qyK7XjAyedS9BMm4/dtqRqcLEMlookL5/N6OX2JM2Gcbv3l4tWWMVxqrTxT4abXfp0YArPwZw9xNF5jsZMLztx04C7RyyAT9cfgfexOley5E5IWva7seUeJwviCGylKdYPSEZ8xr11d6gOoe3kfIJNnC3Fc+lYZ+8SLdfGw0Z3ELvYvafDd6KviKgog7Z136w8QXCB1otQkwx+pNOG2QYHmHeBhnqnlqg7DDYlQZBVCwq0SMl6Fegq8J5K3FYqReV8llmlE1e9NFUGIPf0qKdLRj29GixoApXoYwr5WpZEmZD7Dtrxsc35iFW1IIITIF7AmGyC7nhgFDrhhw3rJDJD1ivWodoyVQzQqai1sO/tYuTxtIwyz3ZTeM6aM+SgmF4FoPALKQ+g=
