language: node_js
sudo: required
dist: trusty
node_js: stable
env:
  global:
    secure: kpz9Y5V1YhA8WXAB1km4sxQUjs2NLU2owG6oQb087FoygtnEjG+pbS4oGanm/LrEkixmBAYQeBWdg/brufv3UfI5Djwi5+fkYSL4utTjfWoc47IPZVIYRFxsJ4wKRnvyBTjz2MM5t/AYVWr99EcitURYPtupz27GQ0AARR+gcSkp2ss8E9QmhxDk7/03mkBH1jA4ToVXWROVGzOvmcU+okwuHxLhvNl0O5rTneJg954jHvRAxQhmrkovUP8R19PZT4FwJdl20wv5Zosk6DS2Z9/MDQIYgwTn8FlRaMWsSoNe1/dBDksl9uhsIeZbQU2rPnT70qaMofmcPPuUFmXg2OvPUTKJo82zXiYjBZhyTckXke4F5JsG7cDiiTluVpg1nQcOgmpKzpb/4t3PuxKoUZpw3DxlsD2C7Em+GbvQiy1DX3f0bL6W2hHw2JvBHw+TCyR/qWrYEowOi1SRO6SfjgK/2eA3rHzz8sKnYwuZnqqziUANrfQdKfAFF96iaSTCnznEmVrT6k5rjSVoiWwVwXnFCdZ9eTkaeG92bsIZsNvp4nzJ0ybjPyDevEoRUdFQaVoNDjG3ASRV0fv9BqRhLIaX7zg2MTNFDAhQF1OO/S7y01D4Wca1OvrbshbhfhISu7U71wsGC7yq2gBuLlR8d1HefEvMAvMjTdoheulacX4=
